import Head from "next/head";
import HomepageHeader from "../../components/homepageHeader";
import ProfileWidget from "../../components/profileWidget";
import FriendSuggestions from "../../components/friendSuggestions";
import IndividualPost from "../../components/individualPost";
import Comment from "../../components/commentComponents/comment";
import CommentForm from "../../components/commentComponents/commentForm";
import useIndividualPost from "../../hooks/useIndividualPost";
import { useRouter } from "next/router";

const IndividualPostPage = () => {
  // Get post_id from router query
  const router = useRouter();
  const { post_id } = router.query;

  // Custom hooks
  const { individualPost } = useIndividualPost(post_id);
  const postData = individualPost.data?.data.post;
  console.log(postData);

  return (
    <>
      <Head>
        <title>Birb Fintech</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomepageHeader />
      <main className="bg-slate-100 min-h-[calc(100vh-72px)] pt-14">
        <div className="max-w-[100rem] mx-auto">
          <div className="grid grid-cols-12 px-5 gap-8 w-full ">
            <ProfileWidget />
            <section className="col-span-full lg:col-span-8 xl:col-span-6 bg-white shadow-xl py-8 rounded-2xl border ">
              <IndividualPost postData={postData} postId={post_id} />
              <CommentForm postId={post_id} />
              <div className="gap-5 px-5 mt-5">
                <h3 className="mb-4 font-medium text-xl">
                  Comments ({postData?.comments.length})
                </h3>
                <div className="flex flex-col gap-5 transition-all">
                  <Comment />
                  <Comment />
                  <Comment />
                </div>
              </div>
            </section>
            <FriendSuggestions />
          </div>
        </div>
      </main>
    </>
  );
};

export default IndividualPostPage;
