import React from "react";
import Head from "next/head";
import useRequireAuth from "../../hooks/useRequireAuth";
import { useAuth } from "../../hooks/useAuth";
import HomepageHeader from "../../components/homepageHeader";
import PostsContainer from "../../components/postsContainer";
import ProfileWidget from "../../components/profileWidget";
import FriendSuggestions from "../../components/friendSuggestions";
import ProfilePopup from "../../components/profilePopup";

const HomePage = () => {
  // Hook will redirect if user not signed in

  const { user } = useAuth();
  console.log(user);

  return (
    <>
      <Head>
        <title>Birb Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomepageHeader />
      <main className="bg-slate-100 min-h-screen pt-14">
        <div className="max-w-[112.5rem] mx-auto">
          <div className="flex justify-between ">
            <ProfileWidget />
            <PostsContainer />
            <FriendSuggestions />
          </div>
        </div>
      </main>
    </>
  );
};

export default HomePage;
