import React from "react";
import Head from "next/head";
import useRequireAuth from "../../hooks/useRequireAuth";
import { useAuth } from "../../hooks/useAuth";
import HomepageHeader from "../../components/homepageHeader";
import PostsContainer from "../../components/postsContainer";

const HomePage = () => {
  // Hook will redirect if user not signed in

  const { user } = useAuth();
  console.log(user);

  return (
    <>
      <Head>
        <title>Birb Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomepageHeader />
      <main className="flex px-3 bg-slate-100 min-h-screen">
        <PostsContainer />
      </main>
    </>
  );
};

export default HomePage;
