import React from "react";
import HomepageHeader from "../../components/homepageHeader";
import Head from "next/head";

const HomePage = () => {
  return (
    <>
      <Head>
        <title>Birb Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomepageHeader />
      <div>
        <div>This is the Home Page</div>
      </div>
    </>
  );
};

export default HomePage;
